# Generated by Django 4.2.1 on 2023-11-18 13:38

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_model',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='writings_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='writing_images')),
                ('title', models.CharField(max_length=50)),
                ('writing', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=50), unique=True)),
                ('categories', models.ManyToManyField(related_name='writing', to='blog.category_model')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'writing',
                'verbose_name_plural': 'writings',
                'db_table': 'writings',
            },
        ),
    ]
