from .contact import contact
from .mainpage import mainpage
from .category import category
from .my_writings import my_writings
from .detail import detail
from .add_writing import add_writing
from .update_writing import update_writing
from .delete_writing import delete_writing
from .delete_comment import delete_comment