from .contact import contact
from .mainpage import mainpage
from .category import category_list_view
from .my_writings import my_writings
from .detail import detail_view
from .add_writing import add_writing_create_view
from .update_writing import update_writing_update_view
from .delete_writing import delete_writing_delete_view
from .delete_comment import delete_comment